-- 에이전시(업체) 정보: 대표 가입 시 생성
CREATE TABLE IF NOT EXISTS admin_agencies (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name     VARCHAR(200) NOT NULL,
    company_slug     VARCHAR(50)  NOT NULL UNIQUE,
    business_number  VARCHAR(12)  NOT NULL UNIQUE,
    address          VARCHAR(500),
    address_detail   VARCHAR(200),
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ALLCREW Admin 회원 (에이전시 대표 / 직원)
CREATE TABLE IF NOT EXISTS admin_members (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id          BIGINT,
    signup_type        VARCHAR(20)  NOT NULL,
    name               VARCHAR(100) NOT NULL,
    phone              VARCHAR(11)  NOT NULL,
    email              VARCHAR(255) NOT NULL UNIQUE,
    password           VARCHAR(255) NOT NULL,
    agree_terms        BOOLEAN      NOT NULL,
    agree_privacy      BOOLEAN      NOT NULL,
    agree_location     BOOLEAN      NOT NULL,
    agree_marketing    BOOLEAN      NOT NULL DEFAULT FALSE,
    invite_code_used   VARCHAR(50),
    member_role        VARCHAR(20)  NOT NULL DEFAULT 'EMPLOYEE',
    is_active          BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at      TIMESTAMP,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_members_signup_type_check
        CHECK (signup_type IN ('REPRESENTATIVE', 'EMPLOYEE')),
    CONSTRAINT admin_members_member_role_check
        CHECK (member_role IN ('REPRESENTATIVE', 'EMPLOYEE')),
    CONSTRAINT admin_members_agency_fkey
        FOREIGN KEY (agency_id) REFERENCES admin_agencies (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_members_agency_id ON admin_members (agency_id);

-- 직원 초대 코드 (대표가 발급, 직원 가입 시 사용)
CREATE TABLE IF NOT EXISTS admin_invite_codes (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id            BIGINT       NOT NULL,
    code                 VARCHAR(50)  NOT NULL UNIQUE,
    created_by_member_id BIGINT,
    expires_at           TIMESTAMP,
    used_at              TIMESTAMP,
    used_by_member_id    BIGINT,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_invite_codes_agency_fkey
        FOREIGN KEY (agency_id) REFERENCES admin_agencies (id),
    CONSTRAINT admin_invite_codes_created_by_fkey
        FOREIGN KEY (created_by_member_id) REFERENCES admin_members (id),
    CONSTRAINT admin_invite_codes_used_by_fkey
        FOREIGN KEY (used_by_member_id) REFERENCES admin_members (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_invite_codes_agency_id ON admin_invite_codes (agency_id);

-- 에이전시 프로젝트
CREATE TABLE IF NOT EXISTS admin_projects (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id                     BIGINT       NOT NULL,
    project_code                  VARCHAR(20)  NOT NULL UNIQUE,
    name                          VARCHAR(200) NOT NULL,
    event_type                    VARCHAR(50)  NOT NULL,
    description                   TEXT,
    cover_image_url               VARCHAR(500),
    start_date                    DATE         NOT NULL,
    end_date                      DATE         NOT NULL,
    work_start_time               TIME         NOT NULL,
    work_end_time                 TIME         NOT NULL,
    address                       VARCHAR(500) NOT NULL,
    address_detail                VARCHAR(200),
    gps_radius                    INT          NOT NULL DEFAULT 100,
    break_minutes                 INT          NOT NULL DEFAULT 60,
    welfare                       VARCHAR(200),
    recruitment_deadline          DATE         NOT NULL,
    preferred_qualifications      TEXT,
    start_recruitment_immediately BOOLEAN      NOT NULL DEFAULT TRUE,
    status                        VARCHAR(20)  NOT NULL DEFAULT 'RECRUITING',
    crew_current                  INT          NOT NULL DEFAULT 0,
    crew_total                    INT          NOT NULL DEFAULT 0,
    budget                        BIGINT       NOT NULL DEFAULT 0,
    progress                      INT          NOT NULL DEFAULT 0,
    created_by_member_id          BIGINT       NOT NULL,
    created_at                    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_projects_agency_fkey
        FOREIGN KEY (agency_id) REFERENCES admin_agencies (id),
    CONSTRAINT admin_projects_created_by_fkey
        FOREIGN KEY (created_by_member_id) REFERENCES admin_members (id),
    CONSTRAINT admin_projects_status_check
        CHECK (status IN ('RECRUITING', 'IN_PROGRESS', 'COMPLETED'))
);

CREATE INDEX IF NOT EXISTS idx_admin_projects_agency_id ON admin_projects (agency_id);

-- 프로젝트 포지션
CREATE TABLE IF NOT EXISTS admin_project_positions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(100) NOT NULL,
    headcount   INT          NOT NULL,
    pay_type    VARCHAR(10)  NOT NULL,
    amount      INT          NOT NULL,
    sort_order  INT          NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_project_positions_project_fkey
        FOREIGN KEY (project_id) REFERENCES admin_projects (id) ON DELETE CASCADE,
    CONSTRAINT admin_project_positions_pay_type_check
        CHECK (pay_type IN ('hourly', 'daily'))
);

CREATE INDEX IF NOT EXISTS idx_admin_project_positions_project_id ON admin_project_positions (project_id);

-- 크루 DB
CREATE TABLE IF NOT EXISTS admin_crew_members (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id        BIGINT       NOT NULL,
    crew_code        VARCHAR(20)  NOT NULL UNIQUE,
    name             VARCHAR(100) NOT NULL,
    phone            VARCHAR(11)  NOT NULL,
    role             VARCHAR(50)  NOT NULL DEFAULT '크루',
    project_count    INT          NOT NULL DEFAULT 0,
    work_days        INT          NOT NULL DEFAULT 0,
    recent_work_date DATE,
    safety_training  VARCHAR(100),
    rating           DECIMAL(2,1) NOT NULL DEFAULT 5.0,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_crew_members_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id)
);

CREATE TABLE IF NOT EXISTS admin_crew_project_links (
    crew_id       BIGINT       NOT NULL,
    project_code  VARCHAR(20)  NOT NULL,
    PRIMARY KEY (crew_id, project_code),
    CONSTRAINT admin_crew_project_links_crew_fkey FOREIGN KEY (crew_id) REFERENCES admin_crew_members (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_admin_crew_members_agency_id ON admin_crew_members (agency_id);

-- 계약
CREATE TABLE IF NOT EXISTS admin_contracts (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id      BIGINT       NOT NULL,
    contract_code  VARCHAR(20)  NOT NULL UNIQUE,
    crew_name      VARCHAR(100) NOT NULL,
    crew_role      VARCHAR(50)  NOT NULL,
    project_name   VARCHAR(200) NOT NULL,
    project_code   VARCHAR(20)  NOT NULL,
    contract_type  VARCHAR(100) NOT NULL DEFAULT '표준 근로',
    sent_date      DATE,
    signed_date    DATE,
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_contracts_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id),
    CONSTRAINT admin_contracts_status_check CHECK (status IN ('SIGNED', 'PENDING', 'UNSIGNED'))
);

CREATE INDEX IF NOT EXISTS idx_admin_contracts_agency_id ON admin_contracts (agency_id);

-- 정산
CREATE TABLE IF NOT EXISTS admin_settlements (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id        BIGINT       NOT NULL,
    settlement_code  VARCHAR(20)  NOT NULL UNIQUE,
    crew_name        VARCHAR(100) NOT NULL,
    crew_role        VARCHAR(50)  NOT NULL,
    work_hours       INT          NOT NULL,
    hourly_rate      INT          NOT NULL,
    pre_tax          BIGINT       NOT NULL,
    deduction        BIGINT       NOT NULL,
    net_pay          BIGINT       NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    project_code     VARCHAR(20)  NOT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_settlements_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id),
    CONSTRAINT admin_settlements_status_check CHECK (status IN ('PENDING', 'APPROVED', 'PAID'))
);

CREATE INDEX IF NOT EXISTS idx_admin_settlements_agency_id ON admin_settlements (agency_id);

-- 채팅방
CREATE TABLE IF NOT EXISTS admin_chat_rooms (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id     BIGINT       NOT NULL,
    room_code     VARCHAR(20)  NOT NULL UNIQUE,
    title         VARCHAR(200) NOT NULL,
    preview       VARCHAR(500) NOT NULL,
    room_time     VARCHAR(20)  NOT NULL,
    room_type     VARCHAR(20)  NOT NULL,
    project_code  VARCHAR(20)  NOT NULL,
    avatar_text   VARCHAR(10)  NOT NULL,
    avatar_color  VARCHAR(20)  NOT NULL,
    crew_code     VARCHAR(20),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_chat_rooms_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id),
    CONSTRAINT admin_chat_rooms_type_check CHECK (room_type IN ('PROJECT', 'DIRECT'))
);

CREATE INDEX IF NOT EXISTS idx_admin_chat_rooms_agency_id ON admin_chat_rooms (agency_id);

CREATE TABLE IF NOT EXISTS admin_chat_messages (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id      BIGINT       NOT NULL,
    sender_type  VARCHAR(20)  NOT NULL,
    sender_name  VARCHAR(100) NOT NULL,
    content      VARCHAR(2000) NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_chat_messages_room_fkey FOREIGN KEY (room_id) REFERENCES admin_chat_rooms (id) ON DELETE CASCADE,
    CONSTRAINT admin_chat_messages_sender_type_check CHECK (sender_type IN ('ADMIN', 'CREW'))
);

CREATE INDEX IF NOT EXISTS idx_admin_chat_messages_room_id ON admin_chat_messages (room_id);

-- 세이프넷
CREATE TABLE IF NOT EXISTS admin_safenet_incidents (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id      BIGINT       NOT NULL,
    incident_code  VARCHAR(20)  NOT NULL UNIQUE,
    title          VARCHAR(200) NOT NULL,
    project_name   VARCHAR(200) NOT NULL,
    location       VARCHAR(200) NOT NULL,
    reporter       VARCHAR(100) NOT NULL,
    incident_time  VARCHAR(20)  NOT NULL,
    status         VARCHAR(20)  NOT NULL DEFAULT 'RESPONDING',
    project_code   VARCHAR(20)  NOT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_safenet_incidents_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id),
    CONSTRAINT admin_safenet_incidents_status_check CHECK (status IN ('RESPONDING', 'CLOSED'))
);

CREATE INDEX IF NOT EXISTS idx_admin_safenet_incidents_agency_id ON admin_safenet_incidents (agency_id);

-- 대시보드 활동 로그
CREATE TABLE IF NOT EXISTS admin_activities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id   BIGINT       NOT NULL,
    content     VARCHAR(500) NOT NULL,
    activity_date DATE       NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_activities_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id)
);

CREATE INDEX IF NOT EXISTS idx_admin_activities_agency_id ON admin_activities (agency_id);

-- 안전교육 설정 (업체/프로젝트)
CREATE TABLE IF NOT EXISTS admin_education_settings (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id    BIGINT       NOT NULL,
    project_code VARCHAR(20),
    ktl_required BOOLEAN      NOT NULL DEFAULT FALSE,
    site_required BOOLEAN     NOT NULL DEFAULT FALSE,
    updated_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_education_settings_agency_fkey FOREIGN KEY (agency_id) REFERENCES admin_agencies (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_admin_education_settings_agency_project
    ON admin_education_settings (agency_id, project_code);















