package com.nodex.allcrew.config

import org.springframework.boot.ApplicationArguments
import org.springframework.boot.ApplicationRunner
import org.springframework.context.annotation.Profile
import org.springframework.jdbc.core.JdbcTemplate
import org.springframework.stereotype.Component

@Component
@Profile("postgres")
class PostgresSchemaMigration(
    private val jdbcTemplate: JdbcTemplate,
) : ApplicationRunner {

    override fun run(args: ApplicationArguments) {
        jdbcTemplate.execute(
            """
            ALTER TABLE admin_chat_rooms
                ADD COLUMN IF NOT EXISTS crew_code VARCHAR(20)
            """.trimIndent(),
        )
        jdbcTemplate.execute(
            """
            CREATE TABLE IF NOT EXISTS admin_chat_messages (
                id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                room_id      BIGINT       NOT NULL,
                sender_type  VARCHAR(20)  NOT NULL,
                sender_name  VARCHAR(100) NOT NULL,
                content      VARCHAR(2000) NOT NULL,
                created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT admin_chat_messages_room_fkey FOREIGN KEY (room_id) REFERENCES admin_chat_rooms (id) ON DELETE CASCADE,
                CONSTRAINT admin_chat_messages_sender_type_check CHECK (sender_type IN ('ADMIN', 'CREW'))
            )
            """.trimIndent(),
        )
        jdbcTemplate.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_admin_chat_messages_room_id ON admin_chat_messages (room_id)
            """.trimIndent(),
        )
    }
}
